version: v0.1
name: preprocess

preprocess:
  lower_bound: -79
  upper_bound: 304
  expand_slice: 20
  target_spacing: [3.0, 1.5, 1.5]
  mean: 101
  std: 76.9
  vol_min: -122.0
  vol_max: 470.0 
  size: 48

create_dataset:
  input_size: [80, 160, 160]
  expand_slice_z: 30
  expand_slice_y: 15
  expand_slice_x: 15
  crop_type: random
  use_bground: True
  z_range: [35, 80]
  y_range: [100, 165]
  x_range: [55, 200]

