version: v0.1
name: kits2019_segment

segment_kits:
  model:
    num_classes: 3
    act_func: softmax
  criterion:
    class_weight: /content/drive/MyDrive/Seg3D/KiTS2019/kits19/output/class_weight.npy
    name: dice_bce
    smooth: 1.e-6
    label_smoothing: 0.01 
  metric: 
    name: dice
    binary: False
  optimizer: 
    name: adam
    lr: 1.e-4
  scheduler: 
    name: reduce_plateu
  verbose: True
  callbacks: [{"name": "checkpoint", "file_path": "output/file_path.pt"}]
  save_path:
    save_log_path: log_UnetRes3D_softmax
    save_model_path: best_UnetRes3D_softmax
    