version: v0.1
name: kits2019_segment

segment_kits:
  model:
    num_classes: 3
    act_func: softmax
  criterion:
    class_weight: output/class_weight.npy
    name: dice_bce
    smooth: 1.e-6
    label_smoothing: 0.01 
  metric: 
    name: dice
    binary: False
  optimizer: 
    name: adam
    lr: 1.e-4
  scheduler: 
    name: reduce_plateu
  verbose: True
  callbacks: [{"name": "report_to_wandb"}, {"name": "lr_finder", "use_plotly": False}]
  save_path:
    save_log_path: log_UnetRes3D_softmax
    save_model_path: best_UnetRes3D_softmax
    